name: human_readable_ids
description: A dart plugin to generate human-readable ids from an english lists of nouns and adjectives.
version: 1.0.0
homepage: https://github.com/evaisse/dart-human-readable-ids

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
